package com.codecool.spingboot_tasks.jdbc_template.repository;

import com.codecool.spingboot_tasks.jdbc_template.model.Product;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.core.namedparam.SqlParameterSource;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Repository;

import javax.sql.DataSource;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Repository
public class ProductRepository {

    private static final String FIND_ALL = "SELECT id, name, price FROM products";
    private static final String FIND_BY_ID = "SELECT id, name, price FROM products WHERE id = :id";
    private static final String CREATE = "INSERT INTO products(name, price) VALUES (:name, :price) RETURNING id";

    private final NamedParameterJdbcTemplate namedTemplate;
    private final JdbcTemplate template;

    @Autowired
    public ProductRepository(DataSource dataSource) {
        this.namedTemplate = new NamedParameterJdbcTemplate(dataSource);
        this.template = new JdbcTemplate(dataSource);
    }

    public List<Product> findAll(){
        MapSqlParameterSource source = new MapSqlParameterSource();
        return namedTemplate.query(FIND_ALL, new ProductRowMapper());
    }

    public List<Integer> findAllPrices(){
        return null;
    }

    public List<String> findAllNames(){
        return null;
    }

    public Product findById(long id) {
        MapSqlParameterSource source = new MapSqlParameterSource();
        source.addValue("id", id);
        final List<Product> products = namedTemplate.query(FIND_BY_ID, source, new ProductRowMapper());
        return products.stream().findFirst().orElseThrow(RuntimeException::new);
    }

    public Product create(Product product) {
        MapSqlParameterSource source = new MapSqlParameterSource();
        source.addValue("name", product.getName());
        source.addValue("price", product.getPrice());
        final List<Integer> query = namedTemplate.query(CREATE, source, new IdRowMapper());
        product.setId(query.stream().findFirst().orElseThrow());
//        product.setId(query.get(0));
        return product;
    }

//    public Product createV2(Product product) { //można skorzystac z SimpleJdbcInsert
//
//        // A way of returning id generated by postgres back to our application
//        KeyHolder keyHolder = new GeneratedKeyHolder();
//
//        template.update(connection -> {
//            PreparedStatement ps = connection.prepareStatement(CREATE, Statement.RETURN_GENERATED_KEYS);
//            ps.setString(1, product.getName());
//            ps.setInt(2, product.getPrice());
//            return ps;
//        }, keyHolder);
//
//        product.setId((Long) keyHolder.getKeyList().get(0).get("id"));
//
//        return product;
//    }
}
